Template.mailModal.events({
  "click #btn-send-email": function(event, template){
    var source_email = template.$('#input-source-email').val();
    var target_email = template.$('#input-target-email').val();

    var qr = $('<div></div>').qrcode({text: 'abc', render: 'table'}).prop('outerHTML');

    Meteor.call('sendEmail',
      target_email,
      source_email,
      "Let's QR!",
      "<p>Hey, look at this QR code generated by letsqr.com!</p>"+qr);

    Meteor.call('trackSentMail', source_email, target_email, $('#input-url').val());

    template.$('#mail-modal').modal('hide');
    alert('Your email has been sent.');
  }
});
