Template.mailModal.events({
  "click #btn-send-email": function(event, template){
    var source_email = template.$('#input-source-email').val();
    var target_email = template.$('#input-target-email').val();

    var input = $('#input-url').val();

    var qr = $('<div></div>').qrcode({text: input, render: 'table'}).prop('outerHTML');
    var email_body = "<p>Hey, look at this QR code generated by letsqr.com!</p>"
                   + qr;

    Meteor.call('sendEmail',
      target_email,
      source_email,
      "Let's QR!",
      email_body);

    Meteor.call('trackSentMail', source_email, target_email, input);

    template.$('#mail-modal').modal('hide');
    alert('Your email has been sent.');
  }
});
